# *************************************
# Charba GitHub Actions build script 
# Copyright © 2020 pepstock.org      
# *************************************
# Workflow name
# 
name: Build
# 
# Runs only on push events on branch 'master'
# 
on:
   push:
      branches:
         - master
         - stock
# 
# Workflow environment and steps
# 
jobs:
   build:
      runs-on: ubuntu-latest
      
      steps:
         # 
         # Checkout the repository content
         # 
         - name: Checkout
           uses: actions/checkout@v2
           with:
             # Disabling shallow clone 
             fetch-depth: 0
         # 
         # Setup Node.js (for Sonar)
         # 
         - name: Setup Node.js
           uses: actions/setup-node@v2    
           with:
             node-version: '12'  
         # 
         # Npm install
         # 
         - name: Npm install
           run: npm install
         # 
         # Run the build of project by ANT
         # 
         - name: Build
           run: npm run build