# *************************************
# Charba GitHub Actions build script 
# Copyright © 2020 pepstock.org      
# *************************************
# Workflow name
# 
name: Deploy
# 
# Runs only on push events on branch 'gh-pages'
# 
on:
   push:
      branches:
         - gh-pages
# 
# Workflow environment and steps
# 
jobs:
   build:
      runs-on: ubuntu-latest
      
      steps:
         # 
         # Checkout the repository content
         # 
         - name: Checkout
           uses: actions/checkout@v2
           with:
             # Disabling shallow clone 
             fetch-depth: 0
         # 
         # Setup Node.js (for Sonar)
         # 
         - name: Setup Node.js
           uses: actions/setup-node@v2    
           with:
             node-version: '12'  
         # 
         # Npm install for Docusaurus
         # 
         - name: Npm install
           run: npm install
         # 
         # Build wiki by Docusaurus
         # 
         - name: Build
           run: npm run build
         # 
         # Build wiki by Docusaurus
         # 
         - name: Deploy to GitHub Pages
           uses: peaceiris/actions-gh-pages@v3
           with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             publish_dir: ./build